version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install -r backend/requirements.txt -t backend/

  build:
    commands:
      - echo "Zipping deployment package..."
      - zip -r deployment.zip backend/ scripts/ appspec.yml

  post_build:
    commands:
      - echo "Uploading to S3..."
      - aws s3 cp deployment.zip s3://demo-09/
      - echo "Build artifact uploaded."

artifacts:
  files:
    - 'appspec.yml'
    - 'deployment.zip'
