AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  WebAppFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: WebAppLambda
      Handler: app.lambda_handler
      Runtime: python3.12
      CodeUri: ./backend
      MemorySize: 128
      Timeout: 10
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        ApiGateway:
          Type: Api
          Properties:
            Path: /
            Method: GET

  DeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties:
      ApplicationName: WebAppDeploy
      DeploymentGroupName: CanaryDeployment
      ServiceRoleArn: !Sub arn:aws:iam::794038224022:role/demo9-codedeploy
      DeploymentConfigName: CodeDeployLambdaCanary10Percent5Minutes
      AutoRollbackConfiguration:
        Enabled: true
        Events:
          - DEPLOYMENT_FAILURE
          - DEPLOYMENT_STOP_ON_REQUEST

  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: WebAppBuild
      Source:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
        Type: LINUX_CONTAINER
      Artifacts:
        Type: CODEPIPELINE
      ServiceRole: !Sub arn:aws:iam::794038224022:role/demo9-codebuild

  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: WebAppPipeline
      RoleArn: !Sub arn:aws:iam::794038224022:role/service-role/demo9-codepipeline
      ArtifactStore:
        Type: S3
        Location: !Sub demo-09
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: '1'
              Configuration:
                Owner: skyskycloud
                Repo: aws-sam-webapp
                Branch: main
                OAuthToken: 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
              OutputArtifacts:
                - Name: SourceOutput
        - Name: Build
          Actions:
            - Name: BuildAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Configuration:
                ProjectName: !Ref demo9
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutput
        - Name: Deploy
          Actions:
            - Name: DeployAction
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CodeDeployToLambda
                Version: '1'
              Configuration:
                ApplicationName: demo9
                DeploymentGroupName: CanaryDeployment
                DeploymentConfigName: CodeDeployDefault.LambdaCanary10Percent5Minutes 
              InputArtifacts:
                - Name: BuildOutput
